package storage

import "errors"

var (
	ErrInvalidAddress    = errors.New("invalid address")
	ErrInvalidBalance    = errors.New("invalid balance")
	ErrMarketNotFound    = errors.New("market not found")
	ErrMarketExists      = errors.New("market already exists")
	ErrMarketNotActive   = errors.New("market is not active")
	ErrMarketNotResolved = errors.New("market is not resolved")
	ErrMarketResolved    = errors.New("market already resolved")
	ErrInvalidOutcome    = errors.New("invalid outcome")
	ErrDisputeWindow     = errors.New("not in dispute window")

	ErrUnauthorized              = errors.New("unauthorized")
	ErrInvalidTokenomicsConfig   = errors.New("invalid tokenomics config")
	ErrInvalidFeeRouterConfig    = errors.New("invalid fee router config")
	ErrInvalidFeeAmount          = errors.New("fee amount must be > 0")
	ErrInvalidReleaseAmount      = errors.New("release amount must be > 0")
	ErrInsufficientLockedCOL     = errors.New("insufficient locked COL")
	ErrReleaseTooEarly           = errors.New("release epoch has not elapsed")
	ErrReleaseCapExceeded        = errors.New("release amount exceeds epoch cap")
	ErrInvalidVAIAmount          = errors.New("VAI amount must be > 0")
	ErrVAIDebtCeilingExceeded    = errors.New("VAI debt ceiling exceeded")
	ErrVAIEpochMintLimitExceeded = errors.New("VAI epoch mint limit exceeded")
	ErrVAIDebtInvariant          = errors.New("VAI debt invariant violation")
	ErrBackingRatioViolation     = errors.New("backing ratio floor violated")
	ErrInvalidRiskConfig         = errors.New("invalid risk config")
	ErrInvalidReserveState       = errors.New("invalid reserve state")
	ErrInvalidReserveUpdate      = errors.New("invalid reserve update")

	ErrUnsupportedAsset       = errors.New("unsupported asset")
	ErrInvalidAssetPair       = errors.New("invalid asset pair")
	ErrInvalidPoolFee         = errors.New("invalid pool fee")
	ErrPoolNotFound           = errors.New("pool not found")
	ErrPoolExists             = errors.New("pool already exists")
	ErrInvalidLiquidityAmount = errors.New("invalid liquidity amount")
	ErrInvalidSwapAmount      = errors.New("invalid swap amount")
	ErrInsufficientLiquidity  = errors.New("insufficient liquidity")
	ErrInsufficientLPBalance  = errors.New("insufficient LP balance")
	ErrSlippageExceeded       = errors.New("slippage exceeded")

	ErrInvalidProofConfig        = errors.New("invalid proof config")
	ErrProofNotFound             = errors.New("batch proof not found")
	ErrProofAlreadySubmitted     = errors.New("batch proof already submitted")
	ErrInvalidProofEnvelope      = errors.New("invalid proof envelope")
	ErrProofTypeMismatch         = errors.New("proof type mismatch")
	ErrProofCircuitMismatch      = errors.New("proof circuit mismatch")
	ErrUnsupportedProofCircuit   = errors.New("unsupported proof circuit")
	ErrProofDeadlineMissed       = errors.New("proof deadline missed")
	ErrProofFillsMismatch        = errors.New("proof/batch fills hash mismatch")
	ErrProofCommitmentMismatch   = errors.New("proof commitment mismatch")
	ErrProofPublicInputsMismatch = errors.New("proof public inputs mismatch")
	ErrProofVerifierUnavailable  = errors.New("proof verifier unavailable")
	ErrProofVerificationFailed   = errors.New("proof verification failed")
	ErrVellumProofNotFound       = errors.New("vellum proof not found")
	ErrInvalidVellumProof        = errors.New("invalid vellum proof")
	ErrInvalidBloodsworn         = errors.New("invalid bloodsworn")
	ErrGlyphNotFound             = errors.New("glyph not found")
	ErrInvalidGlyph              = errors.New("invalid glyph")
)
